source 'https://rubygems.org'

gem 'sqlite3'
gem 'webrick', '>= 1.4.2'
gem 'sinatra'
gem 'sinatra-partial'
gem 'sinatra-contrib'
gem 'sinatra-default_charset'
gem 'bcrypt'
gem 'json'
gem 'openssl', '>= 2.0.6'
gem 'slim'
gem 'rack', '~> 2.0', '>= 2.0.4'
gem 'rack-ssl-enforcer'
gem 'rack-rewrite'