source 'https://rubygems.org'

gem 'sqlite3'
gem 'webrick', '= 1.4.2'
gem 'sinatra'
gem 'sinatra-partial'
gem 'sinatra-contrib'
gem 'sinatra-default_charset'
gem 'bcrypt'
gem 'json'
gem 'openssl'
gem 'slim'
gem 'rack'
gem 'rack-ssl-enforcer'
gem 'rack-rewrite'