source 'https://rubygems.org'

gem 'webrick', '= 1.4.2'
gem 'sinatra'
gem 'sinatra-partial'
gem 'sinatra-contrib'
gem 'sinatra-default_charset'
gem 'data_mapper'
gem 'dm-migrations'
gem 'dm-types'
gem 'dm-aggregates'
gem 'bcrypt'
gem 'json'
gem 'dm-sqlite-adapter'
gem 'openssl'
gem 'slim'
gem 'rack'
gem 'rack-ssl-enforcer'
gem 'rack-rewrite'